# Generated by Django 4.0 on 2021-12-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=30)),
                ('fname', models.CharField(max_length=30)),
                ('mname', models.CharField(max_length=30)),
                ('mobilenum', models.CharField(max_length=11)),
                ('barangay', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('assistance', models.CharField(max_length=30)),
                ('amount', models.IntegerField(max_length=30)),
            ],
        ),
    ]
