# Generated by Django 4.0 on 2021-12-27 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aicsmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='amount',
        ),
    ]
