# Generated by Django 4.0 on 2021-12-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicsmanagement', '0002_remove_beneficiary_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
