# Generated by Django 4.0 on 2022-01-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicsmanagement', '0003_beneficiary_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='barangay',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='mname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='mobilenum',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
